"""Worker task event models."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, TypeAlias


@dataclass(frozen=True, slots=True)
class TaskStarted:
    """Event emitted when a worker task starts.

    ``task_id`` is the unique run identifier (``{name}_{uuid_hex}``) generated by
    ``WorkerTask.__init__`` and bound to Loguru context for the whole run; it lets
    UI handlers and logs correlate events to a specific execution even when the
    same task type is submitted concurrently.
    """

    task_name: str
    task_id: str = ""


@dataclass(frozen=True, slots=True)
class TaskProgress:
    """Event emitted when a worker task reports progress."""

    task_name: str
    task_id: str = ""
    message: str = ""
    current: int | None = None
    total: int | None = None


@dataclass(frozen=True, slots=True)
class TaskCompleted:
    """Event emitted when a worker task completes successfully."""

    task_name: str
    task_id: str = ""
    result: Any = None


@dataclass(frozen=True, slots=True)
class TaskFailed:
    """Event emitted when a worker task fails.

    # field order: non-default (error) must precede defaulted (task_id) —
    # dataclass raises TypeError if defaulted precedes non-default. Reorder
    # only by also adjusting which fields carry defaults.
    """

    task_name: str
    error: Exception
    task_id: str = ""

    @property
    def message(self) -> str:
        """Return a user-readable failure message."""
        return str(self.error)


@dataclass(frozen=True, slots=True)
class TaskCancelled:
    """Event emitted when a worker task is cancelled."""

    task_name: str
    task_id: str = ""
    reason: str = ""


TaskEvent: TypeAlias = TaskStarted | TaskProgress | TaskCompleted | TaskFailed | TaskCancelled
TaskEventHandler: TypeAlias = Callable[[TaskEvent], None]